import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "@/public/style.css";
import { Providers } from "@/Provider";
import "@uploadthing/react/styles.css";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="cupcake">
      <Providers>
        <body className={inter.className}>{children}</body>
      </Providers>
    </html>
  );
}
